version: '3.3'

services:
  php-env:
    build: ./portfolio
    volumes:
      - ./portfolio:/var/www/html
    ports:
      - 8111:80
    depends_on:
      - ujianmcca
  
  ujianmcca:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: personal_portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./portfolio:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8112:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - ujianmcca
