version: '3.8'

services:
  php-env:
    build: ./portfolio
    volumes:
      - .portfolio:/var/www/html
    ports:
      - 8111:80
  
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8112:80
    environment:
      - PMA_ARBITRARY=1
